name: Auto Commit

on:
  schedule:
    - cron: "10 18 * * *"   # Her gün Türkiye saatiyle 21:10 (UTC'de 18:10)
  workflow_dispatch:         # manuel tetikleme opsiyonu

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force a change (log dosyası güncelle)
        run: |
          echo "Last auto commit: $(date)" >> autocommit_log.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto commit $(date)"
          git push
