name: Auto Commit

on:
  schedule:
    - cron: "0 * * * *"   # Her gün Türkiye saatiyle 21:10 (UTC'de 18:10)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Set Git config
        run: |
          git config user.name "jasgues"
          git config user.email "webmanyak@gmail.com"

      - name: Force a change (log dosyası güncelle)
        run: |
          echo "Last auto commit: $(date)" >> autocommit_log.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto commit $(date)" || echo "No changes to commit"
          git push origin main
